version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cnsec
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dmartins1234.
      MYSQL_DATABASE: facturasdb
    ports:
      - "3307:3306"
    networks:
      - cnsec-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-cnsec
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cnsec:3306/facturasdb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dmartins1234.
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: TU_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: TU_SECRET_KEY
      BUCKET_NAME: facturas-app-2025
    ports:
      - "8080:8080"
    networks:
      - cnsec-network
    command: >
      sh -c "echo 'Esperando a MySQL...';
             while ! nc -z mysql-cnsec 3306; do sleep 2; done;
             echo 'MySQL listo, iniciando backend';
             java -jar target/ejemplo-0.0.1-SNAPSHOT.jar"
